#########################
#       general config
#########################
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_common.h)
    option(HAS_URC "build urc task" ON)
endif()

if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_usb_vcom.h)
    option(HAS_USB "build usb task" ON)
endif()


option(HAS_DEMO "build simcom demo" ON)
#########################
# driver
#########################
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_wtd.h)
    option(HAS_DEMO_WTD "build WTD demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/sc_power.h)
    option(HAS_DEMO_PMU "build PMU demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_gpio.h)
    option(HAS_DEMO_GPIO "build GPIO demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_pwm.h)
    option(HAS_DEMO_PWM "build PWM demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_uart.h)
    option(HAS_UART "build UART task" ON)
    option(HAS_DEMO_UART "build UART demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_usb_vcom.h)
    option(HAS_DEMO_USB "build USB demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/sc_i2c.h)
    option(HAS_DEMO_I2C "build I2C demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/sc_spi.h)
    option(HAS_DEMO_SPI "build SPI demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/sc_flash.h)
    option(HAS_DEMO_FLASH "build FLASH demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_fota_download.h)
    option(HAS_DEMO_OTA "build OTA demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_gps.h)
    option(HAS_DEMO_GNSS "build GNSS demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_lcd.h)
    option(HAS_DEMO_LCD "build LCD demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_cam.h)
    option(HAS_DEMO_CAM "build CAM demo" ON)
endif()

#########################
# modem
#########################
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_network.h)
    option(HAS_DEMO_NETWORK "build NETWORK demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_simcard.h)
    option(HAS_DEMO_SIMCARD "build SIMCARD demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_call.h)
    option(HAS_DEMO_CALL "build CALL demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_sms.h)
    option(HAS_DEMO_SMS "build SMS demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_loc.h)
    option(HAS_DEMO_LBS "build LBS demo" ON)
endif()
option(HAS_DEMO_INTERNET_SERVICE "build INTERNET_SERVICE demo" ON)

#########################
# app
#########################
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_ssl.h)
    option(HAS_DEMO_SSL "build SSL demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/scfw_socket.h)
    option(HAS_TCPIP "build TCPIP demo" ON)
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_tcpip.h)
    option(HAS_DEMO_TCPIP "build TCPIP demo" ON)
endif()
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_https.h)
    option(HAS_DEMO_HTTPS "build HTTPS demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_ftps.h)
    option(HAS_DEMO_FTPS "build FTPS demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_mqtts_client.h)
    option(HAS_DEMO_MQTTS "build MQTTS demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_ntp_client.h)
    option(HAS_DEMO_NTP "build NTP demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_htp_client.h)
    option(HAS_DEMO_HTP "build HTP demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_audio.h)
    option(HAS_DEMO_AUDIO "build AUDIO demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_tts.h)
    option(HAS_DEMO_TTS "build TTS demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_poc.h)
    option(HAS_DEMO_POC "build POC demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_wifi.h)
    option(HAS_DEMO_WIFI "build WIFI demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_rtc.h)
    option(HAS_DEMO_RTC "build RTC demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_ble.h)
    option(HAS_DEMO_BLE "build BLE demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/simcom_file.h)
    option(HAS_FS "build FILE_SYSTEM demo" ON)
    option(HAS_DEMO_FS "build FILE_SYSTEM demo" ON)
    option(HAS_DEMO_FS_OLD "build FILE_SYSTEM_OLD demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/sc_app_download.h)
    option(HAS_DEMO_APP_DOWNLOAD "build APP_DOWNLOAD demo" ON)
endif()
if (EXISTS ${CMAKE_SOURCE_DIR}/sc_lib/${SCMODULE}/inc/sc_app_update.h)
    option(HAS_DEMO_APP_UPDATE "build APP_UPDATE demo" ON)
endif()

#########################
# other libs
#########################
if (HAS_FS)
    option(HAS_ZLIB "ZLIB support" OFF)
endif(HAS_FS)

option(HAS_SM2 "SM2 support" OFF)  # is based on miracl
if (HAS_SM2)
    option(HAS_MIRACL "MIRACL LIB" ON)
else(HAS_SM2)
    option(HAS_MIRACL "MIRACL LIB" OFF)
endif(HAS_SM2)
